### PR TITLE
Centralized Export Mods and created mods helper

### PR DESCRIPTION
**Pull request by skelekon**
# Description

.mod files for the 6 new generators now build into .\export\mods\
Added generator for Poisons
Change Basic Weapons to be in a Library instead of Items.

Moved the common functions for those generators into .\helper\mod_helpers.py for ease of maintenance.

## Issue Number
`#7`
`#12`
`#13`

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by skelekon** [comment]
I haven't used github or python before - is this the right way to make more changes?

I really just meant to add the changes that are in 'Build mod files into .\export\mod\'

**Comment by msprijatelj** [comment]
> I haven't used github or python before - is this the right way to make more changes?
> 
> I really just meant to add the changes that are in 'Build mod files into .\export\mod'

Cheers @skelekon ! I'm surprised to hear you haven't used Python before given the huge strides you've made with the Item Generators.  As for GitHub, I recommend setting this repository as an upstream remote repo on your local machine, then pulling the latest changes to your local repo:
```bash
git remote add upstream git@github.com:msprijatelj/4e-module-generator-portable-compendium.git
git pull upstream main
```
This will incorporate all the changes to this repo's `main` branch into your own fork.

**Comment by msprijatelj** [comment]
@skelekon to update, since I performed a Squash Merge, instead of performing a merge to your main branch, you may need to do `git rebase upstream main` instead?

**Comment by msprijatelj** [comment]
Since it includes all basic equipment, regardless of rules source, “Compendium PHB” feels like a misnomer? Even something like “4E Basic Items” or “4E Nonmagical Items” would feel appropriately descriptive. 

Also, minor quibble, but you can import several functions from the same source by using commas instead of using a new line for each:
```python
from source import a, b, c
```

**Comment by skelekon** [comment]
Yeah I see what you're saying - my ultimate goal is to build 3 compendiums to match the usual trinity:
-4E Compendium PHB with everything player facing, including items, powers, feats, etc
-4E Compendium MM with all NPCs
-4E Compendium DMG with anything else DM facing, (I don't know what's left after monsters - traps, terrain maybe?)

That way people with the Compendium files can get everything in Library format, or as much as I can figure out.
(I've just started on adding magic weapons.)

So it's a "Compendium PHB", not a compendium of the "PHB", if that distinction makes sense.

**Comment by msprijatelj** [comment]
That makes sense, and would make it easier to split the mods into sourcebooks down the line like I’d like to do eventually. I would still probably name it “4E Compendium - Players” and “4E Compendium - Monsters” or “GM” so they don’t get conflated with the *actual* PHB, MM, or DMG.

**Comment by skelekon** [comment]
I thought of a different approach last night, and added command line arguments so that the user can specify the Library name and filename, and control what goes into it.
So that should obsolete any issues to do with the library names, etc

```
Usage: module_maker.py [options]

Options:
  -h, --help            show this help message and exit
  -f FILE, --filename=FILE
                        create library at FILE
  -l LIBRARY, --library=LIBRARY
                        Fantasy Grounds' internal name for the Library
  --all                 include all item types in the Library (overrides other
                        item types)
  --armor               include Armor items in the Library
  --equipment           include Equipment items in the Library
  --weapons             include Weapon items in the Library
```

**Review by EthanDunning — APPROVED** [review]

**Comment by msprijatelj** [comment]
@skelekon Is this in a reviewable state? I didn’t know if you had more work to add or not. If everything here is working, I’d like it if any future changes came on a new PR. I’ll review this PR after you give me your go-ahead!

**Comment by skelekon** [comment]
Yes the stuff in this PR should be self-contained and in a (near) final state - I've stopped work on them anyway.

I just deleted the compendium_phb stuff as that's been deprecated by the stuff I'm doing turning the whole thing into a single generic application.

I didn't want to mix the two different designs together - I don't know how best to keep them separate as I've never used git before. Can you fork a second version or something in case these older versions want to live on?

**Comment by msprijatelj** [comment]
> Yes the stuff in this PR should be self-contained and in a (near) final state - I've stopped work on them anyway.
> 
> I just deleted the compendium_phb stuff as that's been deprecated by the stuff I'm doing turning the whole thing into a single generic application.
> 
> I didn't want to mix the two different designs together - I don't know how best to keep them separate as I've never used git before. Can you fork a second version or something in case these older versions want to live on?

I'll work on reviewing this PR when I have time then.  I'll make a dev branch for working on this alternative design; any PRs you make should compare against `msprijatelj/dev` instead of `main`.  Git also provides version control, so any release we make will stick around in the version history.

**Comment by msprijatelj** [comment]
@skelekon Also, I recommend working on your changes on a feature branch of your fork instead of your `main` branch.  In my opinion, it's a little easier to keep your `main` just up to date with the upstream repo (this one) and then create new branches from your `main`.

**Review by msprijatelj — APPROVED** [review]
These are looking good, from what I can tell.  Going merge them in and update the documentation to match!

**Pull request merged**
